-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity backsub_hls_fptoui_float_i8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of backsub_hls_fptoui_float_i8 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal isNeg_fu_72_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isNeg_reg_149 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_109_reg_154 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_159 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_s_fu_32_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal loc_V_1_fu_46_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal p_Result_s_fu_50_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal loc_V_fu_36_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_i_cast1_fu_62_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sh_assign_fu_66_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_i_fu_80_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_cast_fu_86_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sh_assign_1_fu_90_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sh_assign_1_cast_fu_98_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sh_assign_1_cast_cast_fu_102_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_8_i_fu_58_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_1_i_fu_106_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_2_i_fu_110_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_4_i_fu_116_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_fu_140_p1 : STD_LOGIC_VECTOR (7 downto 0);


begin




    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                isNeg_reg_149 <= sh_assign_fu_66_p2(8 downto 8);
                tmp_109_reg_154 <= tmp_2_i_fu_110_p2(23 downto 23);
                tmp_17_reg_159 <= tmp_4_i_fu_116_p2(30 downto 23);
            end if;
        end if;
    end process;
    ap_return <= 
        tmp_fu_140_p1 when (isNeg_reg_149(0) = '1') else 
        tmp_17_reg_159;
    isNeg_fu_72_p3 <= sh_assign_fu_66_p2(8 downto 8);
    loc_V_1_fu_46_p1 <= p_Val2_s_fu_32_p1(23 - 1 downto 0);
    loc_V_fu_36_p4 <= p_Val2_s_fu_32_p1(30 downto 23);
    p_Result_s_fu_50_p3 <= (ap_const_lv1_1 & loc_V_1_fu_46_p1);
    p_Val2_s_fu_32_p1 <= x;
        sh_assign_1_cast_cast_fu_102_p1 <= std_logic_vector(resize(signed(sh_assign_1_fu_90_p3),24));

        sh_assign_1_cast_fu_98_p1 <= std_logic_vector(resize(signed(sh_assign_1_fu_90_p3),32));

    sh_assign_1_fu_90_p3 <= 
        tmp_i_cast_fu_86_p1 when (isNeg_fu_72_p3(0) = '1') else 
        sh_assign_fu_66_p2;
    sh_assign_fu_66_p2 <= std_logic_vector(signed(ap_const_lv9_181) + signed(tmp_i_i_cast1_fu_62_p1));
    tmp_1_i_fu_106_p1 <= std_logic_vector(resize(unsigned(sh_assign_1_cast_fu_98_p1),54));
    tmp_2_i_fu_110_p2 <= std_logic_vector(shift_right(unsigned(p_Result_s_fu_50_p3),to_integer(unsigned('0' & sh_assign_1_cast_cast_fu_102_p1(24-1 downto 0)))));
    tmp_4_i_fu_116_p2 <= std_logic_vector(shift_left(unsigned(tmp_8_i_fu_58_p1),to_integer(unsigned('0' & tmp_1_i_fu_106_p1(31-1 downto 0)))));
    tmp_8_i_fu_58_p1 <= std_logic_vector(resize(unsigned(p_Result_s_fu_50_p3),54));
    tmp_fu_140_p1 <= std_logic_vector(resize(unsigned(tmp_109_reg_154),8));
        tmp_i_cast_fu_86_p1 <= std_logic_vector(resize(signed(tmp_i_fu_80_p2),9));

    tmp_i_fu_80_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(loc_V_fu_36_p4));
    tmp_i_i_cast1_fu_62_p1 <= std_logic_vector(resize(unsigned(loc_V_fu_36_p4),9));
end behav;
