<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="11">
<syndb class_id="0" tracking_level="0" version="0">
	<userIPLatency>-1</userIPLatency>
	<userIPName></userIPName>
	<cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
		<name>backsub_hls_fptoui_float_i8</name>
		<ret_bitwidth>8</ret_bitwidth>
		<ports class_id="2" tracking_level="0" version="0">
			<count>1</count>
			<item_version>0</item_version>
			<item class_id="3" tracking_level="1" version="0" object_id="_1">
				<Value class_id="4" tracking_level="0" version="0">
					<Obj class_id="5" tracking_level="0" version="0">
						<type>1</type>
						<id>1</id>
						<name>x</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo class_id="6" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>x</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs class_id="7" tracking_level="0" version="0">
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
		</ports>
		<nodes class_id="8" tracking_level="0" version="0">
			<count>22</count>
			<item_version>0</item_version>
			<item class_id="9" tracking_level="1" version="0" object_id="_2">
				<Value>
					<Obj>
						<type>0</type>
						<id>2</id>
						<name>x_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>x</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>26</item>
					<item>27</item>
				</oprand_edges>
				<opcode>read</opcode>
			</item>
			<item class_id_reference="9" object_id="_3">
				<Value>
					<Obj>
						<type>0</type>
						<id>3</id>
						<name>p_Val2_s</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>309</lineNumber>
						<contextFuncName>fp_struct</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item class_id="11" tracking_level="0" version="0">
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second class_id="12" tracking_level="0" version="0">
									<count>3</count>
									<item_version>0</item_version>
									<item class_id="13" tracking_level="0" version="0">
										<first class_id="14" tracking_level="0" version="0">
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>390</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
											<second>fp_struct</second>
										</first>
										<second>309</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>val</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>28</item>
				</oprand_edges>
				<opcode>bitcast</opcode>
			</item>
			<item class_id_reference="9" object_id="_4">
				<Value>
					<Obj>
						<type>0</type>
						<id>4</id>
						<name>loc_V</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>316</lineNumber>
						<contextFuncName>fp_struct</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>390</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
											<second>fp_struct</second>
										</first>
										<second>316</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>loc.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>30</item>
					<item>31</item>
					<item>33</item>
					<item>35</item>
				</oprand_edges>
				<opcode>partselect</opcode>
			</item>
			<item class_id_reference="9" object_id="_5">
				<Value>
					<Obj>
						<type>0</type>
						<id>5</id>
						<name>loc_V_1</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>317</lineNumber>
						<contextFuncName>fp_struct</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>390</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
											<second>fp_struct</second>
										</first>
										<second>317</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>loc.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>23</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>36</item>
				</oprand_edges>
				<opcode>trunc</opcode>
			</item>
			<item class_id_reference="9" object_id="_6">
				<Value>
					<Obj>
						<type>0</type>
						<id>6</id>
						<name>p_Result_s</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>364</lineNumber>
						<contextFuncName>mantissa</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>392</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
											<second>mantissa</second>
										</first>
										<second>364</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>__Result__</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>24</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>38</item>
					<item>40</item>
					<item>41</item>
				</oprand_edges>
				<opcode>bitconcatenate</opcode>
			</item>
			<item class_id_reference="9" object_id="_7">
				<Value>
					<Obj>
						<type>0</type>
						<id>7</id>
						<name>tmp_8_i</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>392</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>392</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>54</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>42</item>
				</oprand_edges>
				<opcode>zext</opcode>
			</item>
			<item class_id_reference="9" object_id="_8">
				<Value>
					<Obj>
						<type>0</type>
						<id>8</id>
						<name>tmp_i_i_cast1</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>338</lineNumber>
						<contextFuncName>expv</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>395</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
											<second>expv</second>
										</first>
										<second>338</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>43</item>
				</oprand_edges>
				<opcode>zext</opcode>
			</item>
			<item class_id_reference="9" object_id="_9">
				<Value>
					<Obj>
						<type>0</type>
						<id>9</id>
						<name>sh_assign</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>338</lineNumber>
						<contextFuncName>expv</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>395</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
											<second>expv</second>
										</first>
										<second>338</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>sh</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>45</item>
					<item>46</item>
				</oprand_edges>
				<opcode>add</opcode>
			</item>
			<item class_id_reference="9" object_id="_10">
				<Value>
					<Obj>
						<type>0</type>
						<id>10</id>
						<name>isNeg</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>395</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>395</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>isNeg</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>48</item>
					<item>49</item>
					<item>51</item>
				</oprand_edges>
				<opcode>bitselect</opcode>
			</item>
			<item class_id_reference="9" object_id="_11">
				<Value>
					<Obj>
						<type>0</type>
						<id>11</id>
						<name>tmp_i</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>395</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>395</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>53</item>
					<item>54</item>
				</oprand_edges>
				<opcode>sub</opcode>
			</item>
			<item class_id_reference="9" object_id="_12">
				<Value>
					<Obj>
						<type>0</type>
						<id>12</id>
						<name>tmp_i_cast</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>395</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>395</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>55</item>
				</oprand_edges>
				<opcode>sext</opcode>
			</item>
			<item class_id_reference="9" object_id="_13">
				<Value>
					<Obj>
						<type>0</type>
						<id>13</id>
						<name>sh_assign_1</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>395</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>395</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>sh</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>56</item>
					<item>57</item>
					<item>58</item>
				</oprand_edges>
				<opcode>select</opcode>
			</item>
			<item class_id_reference="9" object_id="_14">
				<Value>
					<Obj>
						<type>0</type>
						<id>14</id>
						<name>sh_assign_1_cast</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>395</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>395</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>59</item>
				</oprand_edges>
				<opcode>sext</opcode>
			</item>
			<item class_id_reference="9" object_id="_15">
				<Value>
					<Obj>
						<type>0</type>
						<id>15</id>
						<name>sh_assign_1_cast_cast</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>395</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>395</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>24</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>60</item>
				</oprand_edges>
				<opcode>sext</opcode>
			</item>
			<item class_id_reference="9" object_id="_16">
				<Value>
					<Obj>
						<type>0</type>
						<id>16</id>
						<name>tmp_1_i</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>395</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>395</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>54</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>61</item>
				</oprand_edges>
				<opcode>zext</opcode>
			</item>
			<item class_id_reference="9" object_id="_17">
				<Value>
					<Obj>
						<type>0</type>
						<id>17</id>
						<name>tmp_2_i</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>395</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>395</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>24</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>62</item>
					<item>63</item>
				</oprand_edges>
				<opcode>lshr</opcode>
			</item>
			<item class_id_reference="9" object_id="_18">
				<Value>
					<Obj>
						<type>0</type>
						<id>18</id>
						<name>tmp_4_i</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>395</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>395</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>54</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>64</item>
					<item>65</item>
				</oprand_edges>
				<opcode>shl</opcode>
			</item>
			<item class_id_reference="9" object_id="_19">
				<Value>
					<Obj>
						<type>0</type>
						<id>19</id>
						<name>tmp_109</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>398</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>398</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>67</item>
					<item>68</item>
					<item>69</item>
				</oprand_edges>
				<opcode>bitselect</opcode>
			</item>
			<item class_id_reference="9" object_id="_20">
				<Value>
					<Obj>
						<type>0</type>
						<id>20</id>
						<name>tmp</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>398</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>398</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>70</item>
				</oprand_edges>
				<opcode>zext</opcode>
			</item>
			<item class_id_reference="9" object_id="_21">
				<Value>
					<Obj>
						<type>0</type>
						<id>21</id>
						<name>tmp_17</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>398</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>398</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>72</item>
					<item>73</item>
					<item>74</item>
					<item>75</item>
				</oprand_edges>
				<opcode>partselect</opcode>
			</item>
			<item class_id_reference="9" object_id="_22">
				<Value>
					<Obj>
						<type>0</type>
						<id>22</id>
						<name>result_V</name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>395</lineNumber>
						<contextFuncName>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/hls/hls_round.h</first>
											<second>cast_IEEE754&amp;lt;unsigned char, float&amp;gt;</second>
										</first>
										<second>395</second>
									</item>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>result.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>76</item>
					<item>77</item>
					<item>78</item>
				</oprand_edges>
				<opcode>select</opcode>
			</item>
			<item class_id_reference="9" object_id="_23">
				<Value>
					<Obj>
						<type>0</type>
						<id>23</id>
						<name></name>
						<fileName>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</fileName>
						<fileDirectory>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</fileDirectory>
						<lineNumber>47</lineNumber>
						<contextFuncName>__hls_fptoui_float_i8</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>/wrk/2015.4/nightly/2015_11_18_1412921/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
											<second>__hls_fptoui_float_i8</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>79</item>
				</oprand_edges>
				<opcode>ret</opcode>
			</item>
		</nodes>
		<consts class_id="15" tracking_level="0" version="0">
			<count>6</count>
			<item_version>0</item_version>
			<item class_id="16" tracking_level="1" version="0" object_id="_24">
				<Value>
					<Obj>
						<type>2</type>
						<id>32</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>23</content>
			</item>
			<item class_id_reference="16" object_id="_25">
				<Value>
					<Obj>
						<type>2</type>
						<id>34</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>30</content>
			</item>
			<item class_id_reference="16" object_id="_26">
				<Value>
					<Obj>
						<type>2</type>
						<id>39</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_27">
				<Value>
					<Obj>
						<type>2</type>
						<id>44</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>385</content>
			</item>
			<item class_id_reference="16" object_id="_28">
				<Value>
					<Obj>
						<type>2</type>
						<id>50</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>8</content>
			</item>
			<item class_id_reference="16" object_id="_29">
				<Value>
					<Obj>
						<type>2</type>
						<id>52</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>127</content>
			</item>
		</consts>
		<blocks class_id="17" tracking_level="0" version="0">
			<count>1</count>
			<item_version>0</item_version>
			<item class_id="18" tracking_level="1" version="0" object_id="_30">
				<Obj>
					<type>3</type>
					<id>24</id>
					<name>backsub___hls_fptoui_float_i8</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>22</count>
					<item_version>0</item_version>
					<item>2</item>
					<item>3</item>
					<item>4</item>
					<item>5</item>
					<item>6</item>
					<item>7</item>
					<item>8</item>
					<item>9</item>
					<item>10</item>
					<item>11</item>
					<item>12</item>
					<item>13</item>
					<item>14</item>
					<item>15</item>
					<item>16</item>
					<item>17</item>
					<item>18</item>
					<item>19</item>
					<item>20</item>
					<item>21</item>
					<item>22</item>
					<item>23</item>
				</node_objs>
			</item>
		</blocks>
		<edges class_id="19" tracking_level="0" version="0">
			<count>37</count>
			<item_version>0</item_version>
			<item class_id="20" tracking_level="1" version="0" object_id="_31">
				<id>27</id>
				<edge_type>1</edge_type>
				<source_obj>1</source_obj>
				<sink_obj>2</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_32">
				<id>28</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>3</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_33">
				<id>31</id>
				<edge_type>1</edge_type>
				<source_obj>3</source_obj>
				<sink_obj>4</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_34">
				<id>33</id>
				<edge_type>1</edge_type>
				<source_obj>32</source_obj>
				<sink_obj>4</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_35">
				<id>35</id>
				<edge_type>1</edge_type>
				<source_obj>34</source_obj>
				<sink_obj>4</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_36">
				<id>36</id>
				<edge_type>1</edge_type>
				<source_obj>3</source_obj>
				<sink_obj>5</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_37">
				<id>40</id>
				<edge_type>1</edge_type>
				<source_obj>39</source_obj>
				<sink_obj>6</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_38">
				<id>41</id>
				<edge_type>1</edge_type>
				<source_obj>5</source_obj>
				<sink_obj>6</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_39">
				<id>42</id>
				<edge_type>1</edge_type>
				<source_obj>6</source_obj>
				<sink_obj>7</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_40">
				<id>43</id>
				<edge_type>1</edge_type>
				<source_obj>4</source_obj>
				<sink_obj>8</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_41">
				<id>45</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>9</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_42">
				<id>46</id>
				<edge_type>1</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>9</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_43">
				<id>49</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>10</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_44">
				<id>51</id>
				<edge_type>1</edge_type>
				<source_obj>50</source_obj>
				<sink_obj>10</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_45">
				<id>53</id>
				<edge_type>1</edge_type>
				<source_obj>52</source_obj>
				<sink_obj>11</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_46">
				<id>54</id>
				<edge_type>1</edge_type>
				<source_obj>4</source_obj>
				<sink_obj>11</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_47">
				<id>55</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>12</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_48">
				<id>56</id>
				<edge_type>1</edge_type>
				<source_obj>10</source_obj>
				<sink_obj>13</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_49">
				<id>57</id>
				<edge_type>1</edge_type>
				<source_obj>12</source_obj>
				<sink_obj>13</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_50">
				<id>58</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>13</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_51">
				<id>59</id>
				<edge_type>1</edge_type>
				<source_obj>13</source_obj>
				<sink_obj>14</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_52">
				<id>60</id>
				<edge_type>1</edge_type>
				<source_obj>13</source_obj>
				<sink_obj>15</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_53">
				<id>61</id>
				<edge_type>1</edge_type>
				<source_obj>14</source_obj>
				<sink_obj>16</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_54">
				<id>62</id>
				<edge_type>1</edge_type>
				<source_obj>6</source_obj>
				<sink_obj>17</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_55">
				<id>63</id>
				<edge_type>1</edge_type>
				<source_obj>15</source_obj>
				<sink_obj>17</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_56">
				<id>64</id>
				<edge_type>1</edge_type>
				<source_obj>7</source_obj>
				<sink_obj>18</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_57">
				<id>65</id>
				<edge_type>1</edge_type>
				<source_obj>16</source_obj>
				<sink_obj>18</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_58">
				<id>68</id>
				<edge_type>1</edge_type>
				<source_obj>17</source_obj>
				<sink_obj>19</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_59">
				<id>69</id>
				<edge_type>1</edge_type>
				<source_obj>32</source_obj>
				<sink_obj>19</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_60">
				<id>70</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>20</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_61">
				<id>73</id>
				<edge_type>1</edge_type>
				<source_obj>18</source_obj>
				<sink_obj>21</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_62">
				<id>74</id>
				<edge_type>1</edge_type>
				<source_obj>32</source_obj>
				<sink_obj>21</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_63">
				<id>75</id>
				<edge_type>1</edge_type>
				<source_obj>34</source_obj>
				<sink_obj>21</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_64">
				<id>76</id>
				<edge_type>1</edge_type>
				<source_obj>10</source_obj>
				<sink_obj>22</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_65">
				<id>77</id>
				<edge_type>1</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>22</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_66">
				<id>78</id>
				<edge_type>1</edge_type>
				<source_obj>21</source_obj>
				<sink_obj>22</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_67">
				<id>79</id>
				<edge_type>1</edge_type>
				<source_obj>22</source_obj>
				<sink_obj>23</sink_obj>
			</item>
		</edges>
	</cdfg>
	<cdfg_regions class_id="21" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="22" tracking_level="1" version="0" object_id="_68">
			<mId>1</mId>
			<mTag>backsub___hls_fptoui_float_i8</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>24</item>
			</basic_blocks>
			<mII>1</mII>
			<mDepth>2</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>1</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
	</cdfg_regions>
	<fsm class_id="-1"></fsm>
	<res class_id="-1"></res>
	<node_label_latency class_id="26" tracking_level="0" version="0">
		<count>22</count>
		<item_version>0</item_version>
		<item class_id="27" tracking_level="0" version="0">
			<first>2</first>
			<second class_id="28" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>3</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>4</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>5</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>6</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>7</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>8</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>9</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>10</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>11</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>12</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>13</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>14</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>15</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>16</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>17</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>18</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>19</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>20</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>21</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>22</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>23</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
	</node_label_latency>
	<bblk_ent_exit class_id="29" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="30" tracking_level="0" version="0">
			<first>24</first>
			<second class_id="31" tracking_level="0" version="0">
				<first>0</first>
				<second>1</second>
			</second>
		</item>
	</bblk_ent_exit>
	<regions class_id="32" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="33" tracking_level="1" version="0" object_id="_69">
			<region_name>backsub___hls_fptoui_float_i8</region_name>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>24</item>
			</basic_blocks>
			<nodes>
				<count>0</count>
				<item_version>0</item_version>
			</nodes>
			<anchor_node>-1</anchor_node>
			<region_type>8</region_type>
			<interval>1</interval>
			<pipe_depth>2</pipe_depth>
		</item>
	</regions>
	<dp_fu_nodes class_id="34" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes>
	<dp_fu_nodes_expression class_id="35" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_expression>
	<dp_fu_nodes_module>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_module>
	<dp_fu_nodes_io>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_io>
	<return_ports>
		<count>0</count>
		<item_version>0</item_version>
	</return_ports>
	<dp_mem_port_nodes class_id="36" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_mem_port_nodes>
	<dp_reg_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_nodes>
	<dp_regname_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_nodes>
	<dp_reg_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_phi>
	<dp_regname_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_phi>
	<dp_port_io_nodes class_id="37" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_port_io_nodes>
	<port2core class_id="38" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</port2core>
	<node2core>
		<count>0</count>
		<item_version>0</item_version>
	</node2core>
</syndb>
</boost_serialization>

