// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "gmem"
#define AUTOTB_TVIN_gmem  "../tv/cdatafile/c.backsub.autotvin_gmem.dat"
// wrapc file define: "gmem_offset"
#define AUTOTB_TVOUT_gmem_offset  "../tv/cdatafile/c.backsub.autotvout_gmem_offset.dat"
#define AUTOTB_TVIN_gmem_offset  "../tv/cdatafile/c.backsub.autotvin_gmem_offset.dat"
// wrapc file define: "frame_in"
#define AUTOTB_TVIN_frame_in  "../tv/cdatafile/c.backsub.autotvin_frame_in.dat"
// wrapc file define: "frame_out"
#define AUTOTB_TVIN_frame_out  "../tv/cdatafile/c.backsub.autotvin_frame_out.dat"
// wrapc file define: "frame"
#define AUTOTB_TVIN_frame  "../tv/cdatafile/c.backsub.autotvin_frame.dat"
#define AUTOTB_TVOUT_frame  "../tv/cdatafile/c.backsub.autotvout_frame.dat"
// wrapc file define: "init"
#define AUTOTB_TVIN_init  "../tv/cdatafile/c.backsub.autotvin_init.dat"
// wrapc file define: "ap_return"
#define AUTOTB_TVOUT_ap_return  "../tv/cdatafile/c.backsub.autotvout_ap_return.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "gmem_offset"
#define AUTOTB_TVOUT_PC_gmem_offset  "../tv/rtldatafile/rtl.backsub.autotvout_gmem_offset.dat"
// tvout file define: "frame"
#define AUTOTB_TVOUT_PC_frame  "../tv/rtldatafile/rtl.backsub.autotvout_frame.dat"
// tvout file define: "ap_return"
#define AUTOTB_TVOUT_PC_ap_return  "../tv/rtldatafile/rtl.backsub.autotvout_ap_return.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			gmem_depth = 0;
			gmem_offset_depth = 0;
			frame_in_depth = 0;
			frame_out_depth = 0;
			frame_depth = 0;
			init_depth = 0;
			ap_return_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{gmem " << gmem_depth << "}\n";
			total_list << "{gmem_offset " << gmem_offset_depth << "}\n";
			total_list << "{frame_in " << frame_in_depth << "}\n";
			total_list << "{frame_out " << frame_out_depth << "}\n";
			total_list << "{frame " << frame_depth << "}\n";
			total_list << "{init " << init_depth << "}\n";
			total_list << "{ap_return " << ap_return_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int gmem_depth;
		int gmem_offset_depth;
		int frame_in_depth;
		int frame_out_depth;
		int frame_depth;
		int init_depth;
		int ap_return_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};


#define backsub AESL_ORIG_DUT_backsub
extern int backsub (
unsigned int* frame_in,
unsigned char* frame_out,
unsigned short frame[76800],
bool init);
#undef backsub

int backsub (
unsigned int* frame_in,
unsigned char* frame_out,
unsigned short frame[76800],
bool init)
{
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		int AESL_return;

		// output port post check: "gmem_offset"
		aesl_fh.read(AUTOTB_TVOUT_PC_gmem_offset, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_gmem_offset, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_gmem_offset, AESL_token); // data

			sc_bv<8> *gmem_offset_pc_buffer = new sc_bv<8>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'gmem_offset', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'gmem_offset', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					gmem_offset_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_gmem_offset, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_gmem_offset))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: gmem_offset
				{
					// bitslice(7, 0)
					// {
						// celement: frame_out(7, 0)
						// {
							sc_lv<8>* frame_out_lv0_0_0_1 = new sc_lv<8>[1];
						// }
					// }

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: frame_out(7, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(frame_out[0]) != NULL) // check the null address if the c port is array or others
								{
									frame_out_lv0_0_0_1[hls_map_index++].range(7, 0) = sc_bv<8>(gmem_offset_pc_buffer[hls_map_index].range(7, 0));
								}
							}
						}
					}

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: frame_out(7, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : frame_out[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : frame_out[0]
								// output_left_conversion : frame_out[i_0]
								// output_type_conversion : (frame_out_lv0_0_0_1[hls_map_index++]).to_uint64()
								if (&(frame_out[0]) != NULL) // check the null address if the c port is array or others
								{
									frame_out[i_0] = (frame_out_lv0_0_0_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] gmem_offset_pc_buffer;
		}

		// output port post check: "frame"
		aesl_fh.read(AUTOTB_TVOUT_PC_frame, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_frame, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_frame, AESL_token); // data

			sc_bv<16> *frame_pc_buffer = new sc_bv<16>[76800];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'frame', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'frame', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					frame_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_frame, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_frame))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: frame
				{
					// bitslice(15, 0)
					// {
						// celement: frame(15, 0)
						// {
							sc_lv<16>* frame_lv0_0_76799_1 = new sc_lv<16>[76800];
						// }
					// }

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: frame(15, 0)
						{
							// carray: (0) => (76799) @ (1)
							for (int i_0 = 0; i_0 <= 76799; i_0 += 1)
							{
								if (&(frame[0]) != NULL) // check the null address if the c port is array or others
								{
									frame_lv0_0_76799_1[hls_map_index++].range(15, 0) = sc_bv<16>(frame_pc_buffer[hls_map_index].range(15, 0));
								}
							}
						}
					}

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: frame(15, 0)
						{
							// carray: (0) => (76799) @ (1)
							for (int i_0 = 0; i_0 <= 76799; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : frame[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : frame[0]
								// output_left_conversion : frame[i_0]
								// output_type_conversion : (frame_lv0_0_76799_1[hls_map_index++]).to_uint64()
								if (&(frame[0]) != NULL) // check the null address if the c port is array or others
								{
									frame[i_0] = (frame_lv0_0_76799_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] frame_pc_buffer;
		}

		// output port post check: "ap_return"
		aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // data

			sc_bv<32> ap_return_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					ap_return_pc_buffer = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_ap_return))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: ap_return
				{
					// bitslice(31, 0)
					// {
						// celement: return(31, 0)
						// {
							sc_lv<32> return_lv0_0_1_0;
						// }
					// }

					// bitslice(31, 0)
					{
						// celement: return(31, 0)
						{
							// carray: (0) => (1) @ (0)
							{
								if (&(AESL_return) != NULL) // check the null address if the c port is array or others
								{
									return_lv0_0_1_0.range(31, 0) = sc_bv<32>(ap_return_pc_buffer.range(31, 0));
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						// celement: return(31, 0)
						{
							// carray: (0) => (1) @ (0)
							{
								// sub                    : 
								// ori_name               : AESL_return
								// sub_1st_elem           : 
								// ori_name_1st_elem      : AESL_return
								// output_left_conversion : AESL_return
								// output_type_conversion : (return_lv0_0_1_0).to_uint64()
								if (&(AESL_return) != NULL) // check the null address if the c port is array or others
								{
									AESL_return = (return_lv0_0_1_0).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		AESL_transaction_pc++;

		return AESL_return;
	}
	else
	{
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "gmem"
		char* tvin_gmem = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_gmem);

		// "gmem_offset"
		char* tvin_gmem_offset = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_gmem_offset);
		char* tvout_gmem_offset = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_gmem_offset);

		// "frame_in"
		char* tvin_frame_in = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_frame_in);

		// "frame_out"
		char* tvin_frame_out = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_frame_out);

		// "frame"
		char* tvin_frame = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_frame);
		char* tvout_frame = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_frame);

		// "init"
		char* tvin_init = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_init);

		// "ap_return"
		char* tvout_ap_return = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_ap_return);

		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_gmem, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_gmem, tvin_gmem);

		sc_bv<32>* gmem_tvin_wrapc_buffer = new sc_bv<32>[1];

		// RTL Name: gmem
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: frame_in(31, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : frame_in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : frame_in[0]
						// regulate_c_name       : frame_in
						// input_type_conversion : frame_in[i_0]
						if (&(frame_in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> frame_in_tmp_mem;
							frame_in_tmp_mem = frame_in[i_0];
							gmem_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = frame_in_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_gmem, "%s\n", (gmem_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_gmem, tvin_gmem);
		}

		tcl_file.set_num(1, &tcl_file.gmem_depth);
		sprintf(tvin_gmem, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_gmem, tvin_gmem);

		// release memory allocation
		delete [] gmem_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_gmem_offset, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_gmem_offset, tvin_gmem_offset);

		sc_bv<8>* gmem_offset_tvin_wrapc_buffer = new sc_bv<8>[1];

		// RTL Name: gmem_offset
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: frame_out(7, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : frame_out[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : frame_out[0]
						// regulate_c_name       : frame_out
						// input_type_conversion : frame_out[i_0]
						if (&(frame_out[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> frame_out_tmp_mem;
							frame_out_tmp_mem = frame_out[i_0];
							gmem_offset_tvin_wrapc_buffer[hls_map_index++].range(7, 0) = frame_out_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_gmem_offset, "%s\n", (gmem_offset_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_gmem_offset, tvin_gmem_offset);
		}

		tcl_file.set_num(1, &tcl_file.gmem_offset_depth);
		sprintf(tvin_gmem_offset, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_gmem_offset, tvin_gmem_offset);

		// release memory allocation
		delete [] gmem_offset_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_frame_in, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_frame_in, tvin_frame_in);

		sc_bv<32> frame_in_tvin_wrapc_buffer;

		// RTL Name: frame_in
		{
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_frame_in, "%s\n", (frame_in_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_frame_in, tvin_frame_in);
		}

		tcl_file.set_num(1, &tcl_file.frame_in_depth);
		sprintf(tvin_frame_in, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_frame_in, tvin_frame_in);

		// [[transaction]]
		sprintf(tvin_frame_out, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_frame_out, tvin_frame_out);

		sc_bv<32> frame_out_tvin_wrapc_buffer;

		// RTL Name: frame_out
		{
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_frame_out, "%s\n", (frame_out_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_frame_out, tvin_frame_out);
		}

		tcl_file.set_num(1, &tcl_file.frame_out_depth);
		sprintf(tvin_frame_out, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_frame_out, tvin_frame_out);

		// [[transaction]]
		sprintf(tvin_frame, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_frame, tvin_frame);

		sc_bv<16>* frame_tvin_wrapc_buffer = new sc_bv<16>[76800];

		// RTL Name: frame
		{
			// bitslice(15, 0)
			{
				int hls_map_index = 0;
				// celement: frame(15, 0)
				{
					// carray: (0) => (76799) @ (1)
					for (int i_0 = 0; i_0 <= 76799; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : frame[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : frame[0]
						// regulate_c_name       : frame
						// input_type_conversion : frame[i_0]
						if (&(frame[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> frame_tmp_mem;
							frame_tmp_mem = frame[i_0];
							frame_tvin_wrapc_buffer[hls_map_index++].range(15, 0) = frame_tmp_mem.range(15, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 76800; i++)
		{
			sprintf(tvin_frame, "%s\n", (frame_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_frame, tvin_frame);
		}

		tcl_file.set_num(76800, &tcl_file.frame_depth);
		sprintf(tvin_frame, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_frame, tvin_frame);

		// release memory allocation
		delete [] frame_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_init, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_init, tvin_init);

		sc_bv<1> init_tvin_wrapc_buffer;

		// RTL Name: init
		{
			// bitslice(0, 0)
			{
				// celement: init(0, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : init
						// sub_1st_elem          : 
						// ori_name_1st_elem     : init
						// regulate_c_name       : init
						// input_type_conversion : init
						if (&(init) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<1> init_tmp_mem;
							init_tmp_mem = init;
							init_tvin_wrapc_buffer.range(0, 0) = init_tmp_mem.range(0, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_init, "%s\n", (init_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_init, tvin_init);
		}

		tcl_file.set_num(1, &tcl_file.init_depth);
		sprintf(tvin_init, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_init, tvin_init);

// [call_c_dut] ---------->

		int AESL_return = AESL_ORIG_DUT_backsub(frame_in, frame_out, frame, init);


		// [[transaction]]
		sprintf(tvout_gmem_offset, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_gmem_offset, tvout_gmem_offset);

		sc_bv<8>* gmem_offset_tvout_wrapc_buffer = new sc_bv<8>[1];

		// RTL Name: gmem_offset
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: frame_out(7, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : frame_out[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : frame_out[0]
						// regulate_c_name       : frame_out
						// input_type_conversion : frame_out[i_0]
						if (&(frame_out[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> frame_out_tmp_mem;
							frame_out_tmp_mem = frame_out[i_0];
							gmem_offset_tvout_wrapc_buffer[hls_map_index++].range(7, 0) = frame_out_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_gmem_offset, "%s\n", (gmem_offset_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_gmem_offset, tvout_gmem_offset);
		}

		tcl_file.set_num(1, &tcl_file.gmem_offset_depth);
		sprintf(tvout_gmem_offset, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_gmem_offset, tvout_gmem_offset);

		// release memory allocation
		delete [] gmem_offset_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_frame, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_frame, tvout_frame);

		sc_bv<16>* frame_tvout_wrapc_buffer = new sc_bv<16>[76800];

		// RTL Name: frame
		{
			// bitslice(15, 0)
			{
				int hls_map_index = 0;
				// celement: frame(15, 0)
				{
					// carray: (0) => (76799) @ (1)
					for (int i_0 = 0; i_0 <= 76799; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : frame[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : frame[0]
						// regulate_c_name       : frame
						// input_type_conversion : frame[i_0]
						if (&(frame[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> frame_tmp_mem;
							frame_tmp_mem = frame[i_0];
							frame_tvout_wrapc_buffer[hls_map_index++].range(15, 0) = frame_tmp_mem.range(15, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 76800; i++)
		{
			sprintf(tvout_frame, "%s\n", (frame_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_frame, tvout_frame);
		}

		tcl_file.set_num(76800, &tcl_file.frame_depth);
		sprintf(tvout_frame, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_frame, tvout_frame);

		// release memory allocation
		delete [] frame_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_ap_return, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

		sc_bv<32> ap_return_tvout_wrapc_buffer;

		// RTL Name: ap_return
		{
			// bitslice(31, 0)
			{
				// celement: return(31, 0)
				{
					// carray: (0) => (1) @ (0)
					{
						// sub                   : 
						// ori_name              : AESL_return
						// sub_1st_elem          : 
						// ori_name_1st_elem     : AESL_return
						// regulate_c_name       : return
						// input_type_conversion : AESL_return
						if (&(AESL_return) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> return_tmp_mem;
							return_tmp_mem = AESL_return;
							ap_return_tvout_wrapc_buffer.range(31, 0) = return_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_ap_return, "%s\n", (ap_return_tvout_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);
		}

		tcl_file.set_num(1, &tcl_file.ap_return_depth);
		sprintf(tvout_ap_return, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

		// release memory allocation: "gmem"
		delete [] tvin_gmem;
		// release memory allocation: "gmem_offset"
		delete [] tvout_gmem_offset;
		delete [] tvin_gmem_offset;
		// release memory allocation: "frame_in"
		delete [] tvin_frame_in;
		// release memory allocation: "frame_out"
		delete [] tvin_frame_out;
		// release memory allocation: "frame"
		delete [] tvin_frame;
		delete [] tvout_frame;
		// release memory allocation: "init"
		delete [] tvin_init;
		// release memory allocation: "ap_return"
		delete [] tvout_ap_return;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);

		return AESL_return;
	}
}

