// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

extern int backsub (
unsigned int* frame_in,
unsigned char* frame_out,
unsigned short frame[76800],
bool init);
